version: '3'
services:
  minio:
    platform: linux/x86_64
    image: bitnami/minio:latest
    container_name: minio-container
    environment:
      - MINIO_ROOT_USER=cristian
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=nycdatatrip
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data


volumes:
  minio-data:
    driver: local